# Generated by Django 4.2.5 on 2023-10-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
